apiVersion: v1
kind: Service
metadata:
  name: backend-image-filter
  labels:
    app: backend-image-filter
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: backend-image-filter